### ISSUE TITLE
Nombres de contexto de snapshots y último snapshot repetido

### ISSUE THREAD

**Issue by rodri042** [gobstones/gobstones-interpreter#11]
Es un detalle pero es importante para poder mostrar algunos procedimientos como atómicos:

El código:

```
procedure MoverTresAtomico() {
  Mover(Norte)
  Mover(Norte)
  Mover(Norte)
}

program {
    Poner(Verde)
    MoverTresAtomico()
    Poner(Negro)
}
```

está generando los siguientes snapshots:

```json
[
  {
    "contextNames": ["program" ],
    "board": ...
  },
  {
    "contextNames": ["program"],
    "board": ...
  },
  {
    "contextNames": ["program", "MoverTresAtomico-1"],
    "board": ...
  },
  {
    "contextNames": ["program", "MoverTresAtomico-2"],
    "board": ...
  },
  {
    "contextNames": ["program", "MoverTresAtomico-3"],
    "board": ...
  },
  {
    "contextNames": ["program"],
    "board": ...
  },
  {
    "contextNames": ["program"],
    "board": ...
  }
]
```

Debería generar:

```json
[
  {
    "contextNames": ["program" ],
    "board": ...
  },
  {
    "contextNames": ["program"],
    "board": ...
  },
  {
    "contextNames": ["program", "MoverTresAtomico-1"],
    "board": ...
  },
  {
    "contextNames": ["program", "MoverTresAtomico-1"],
    "board": ...
  },
  {
    "contextNames": ["program", "MoverTresAtomico-1"],
    "board": ...
  },
  {
    "contextNames": ["program"],
    "board": ...
  }
]
```

Las correcciones fueron:
- El id del final tiene que generarse una sola vez al momento de entrar al stack y mantenerse en todas sus snapshots. Si sale de la llamada y vuelve a entrar al mismo procedimiento pero otra llamada, ahí sí se genera un id nuevo. Ejemplo:
```
MoverTresAtomico() // los 3 snapshots se reportan con MoverTresAtomico-1
MoverTresAtomico() // los 3 snapshots se reportan con MoverTresAtomico-2
Poner(Rojo)
MoverTresAtomico() // los 3 snapshots se reportan con MoverTresAtomico-3
```
El id no es necesario que sea autonumérico: puede ser un timestamp, uuid, o cualquier cosa (aclaro por si eso hace más fácil el cambio).

- Tiene que generar 6 snapshots en vez de 7. En la implementación actual, el último es siempre igual al anteúltimo (el anteúltimo ya es el tablero final).

**Comment by fidel-ml** [comment]
¿Para qué son los snapshots? Porque si es atómico, suena a que tendría que
tener UN solo snapshot y no 3...

**Comment by rodri042** [comment]
Algo interno que uso del intérprete. Es una foto de cada estado intermedio por el que pasa el tablero. Pablo me pasa todos y yo debo ignorar los estados no-finales de los procedimientos atómicos.

Lo mejor sería que directamente me pase él uno solo, sí, pero eso implicaría que el intérprete tiene que tener conocimiento sobre cuáles procedimientos son atómicos y cuáles no, y eso decidimos postergarlo para tener una primera integración andando.
