### ISSUE TITLE
Error al leer algunos GBB

### ISSUE THREAD

**Issue by rodri042** [gobstones/gobstones-interpreter#12]
```
GBB/1.0
size 10 2
cell 9 1 Azul 10 Negro 0 Rojo 0 Verde 0
cell 8 1 Azul 9 Negro 0 Rojo 0 Verde 0
cell 7 1 Azul 8 Negro 0 Rojo 0 Verde 0
cell 6 1 Azul 7 Negro 0 Rojo 0 Verde 0
cell 5 1 Azul 6 Negro 0 Rojo 0 Verde 0
cell 4 1 Azul 5 Negro 0 Rojo 0 Verde 0
cell 3 1 Azul 4 Negro 0 Rojo 0 Verde 0
cell 2 1 Azul 3 Negro 0 Rojo 0 Verde 0
cell 1 1 Azul 2 Negro 0 Rojo 0 Verde 0
cell 0 1 Azul 1 Negro 0 Rojo 1 Verde 0
head 0 0
```

Esto rompe con `Error: GBB/1.0: Board lacks a size declaration.`

Al parecer está leyendo un token vacío en vez de la palabra size.
![screenshot1](https://user-images.githubusercontent.com/1631752/33193584-6a8a0790-d0d2-11e7-967d-29bb937a8f1f.png)

Se me hace que tiene que ver con los newlines de Windows, pero no sé.

**Comment by rodri042** [comment]
Sí, ahí vi que es GBB válido. Edito el issue

**Comment by fidel-ml** [comment]
[image: Web Bug from
https://github.com/notifications/beacon/AIaqtmCOb54J67voAglPFGFxQtwwC35Sks5s5iyJgaJpZM4QpUF8.gif]Es
un tablero correctísimo. El size va siempre primero.
Y así como está, a mí me anda (lo copié y pegué en un proyecto nuevo, y
cargó lo más bien...).
¿Dónde falló? ¿En qué condiciones?

**Comment by fidel-ml** [comment]
Ahí tuve un error de lectura del tablero en la versión
https://gobstones.github.io/gobstones-web-con-interprete-nuevo/#/code. Debe
ser un bug en el InitialBoardLoader. El error que me tira es:

InitialBoardLoader Error: GBB/1.0: Board not in GBB/1.0 format.
    at gbbToJboard (elements.html:44581)
    at Object.read (elements.html:37647)
    at Parser.readGbb (elements.html:44787)
    at InitialBoardLoader.readContent (elements.html:44881)
    at InitialBoardLoader.readProjectContent (elements.html:44892)
    at elements.html:45264
    at <anonymous>

Pero en las otras versiones, anda...

**Comment by rodri042** [comment]
@fidel-ml, en las otras versiones andan porque usan el intérprete viejo...

Ahora el nuevo solo está subido temporalmente a https://gobstones.github.io/gobstones-web-con-interprete-nuevo hasta que terminemos de arreglar todo.
