### ISSUE TITLE
Switch con literal numérico

### ISSUE THREAD

**Issue by rodri042** [gobstones/gobstones-interpreter#17]
El programa:

```
program{
    a := 2
    switch(a) to {
        2 -> {
            Poner(Rojo)
        }
    }
}
```

... tira error de compilación diciendo que "2" no es un valor válido para una branch.

El resto de los literales funcionan bien (colores, direcciones, booleanos).

**Comment by foones** [comment]
No recuerdo haberlo hablado explícitamente con @fidel-ml pero en principio el switch de números fue excluido conscientemente. Los casos como los que mencionás se escribirían usando `if ... else if ... else ...`. No estoy en contra de agregar switch para números, pero habría que determinar cómo.

El motivo es que el switch es el eliminador de los tipos `variant`, que están definidos como una unión disjunta de varios casos. Por ejemplo, los colores en Gobstones ya vienen predefinidos, pero internamente están definidos así:

`type Color is variant { case Azul {} case Negro {} case Rojo {} case Verde {}}`

_Nota:_ al menos en la filosofía de este intérprete los tipos `record` también son casos particulares de tipos `variant`, que tienen un único caso, es decir `type A is record {...}` no es otra cosa que syntax sugar para `type A is variant { case A { ... } }`.

Los números en Gobstones no son tipos variant: hay al menos dos formas de pensarlos como tipos variant, y ninguna termina de cerrar.

Una manera es pensar que están construidos recursivamente, por ejemplo usando Cero y Sucesor. Un problema de esto es que en Gobstones no queremos trabajar con tipos de datos recursivos (mismo motivo por el cual no se permite hacer pattern matching sobre listas). Otro problema es que en Gobstones también hay números negativos, que tradicionalmente se construyen en dos capas, empezando primero por los números los naturales (de manera que un esquema simple como el de Cero y Sucesor no alcanza para Gobstones). Otro problema es que al hacer `switch (a) to { 2 -> ... }`, el patrón para el número `2` sería conceptualmente un patrón "anidado" (tipo Suc(Suc(Cero))), cosa que no estamos permitiendo.

La otra manera es pensar que los números son un tipo variant construido con un número infinito de constructores (0, 1, -1, 2, -2, ...). Esto se lleva bastante bien con el resto del lenguaje, salvo por el hecho de que los números necesariamente tienen que estar predefinidos. Creo que estoy a favor de agregar `switch` sobre números con esta interpretación. En ese caso también estoy a favor de agregar `switch` sobre strings, con la misma filosofía.

**Comment by fidel-ml** [comment]
Sobre números era parte del Gobstones original, así que si estás de
acuerdo, vamos con el switch.
Sobre strings no, porque la idea es no permitir ninguna computación
dependiente de strings. De hecho, creo que ni la igualdad debería
funcionar...
Strings es un mundo a discutir...
FF


On Dec 20, 2017 11:39, "foones" <notifications@github.com> wrote:

No recuerdo haberlo hablado explícitamente con @fidel-ml
<https://github.com/fidel-ml> pero en principio el switch de números fue
excluido conscientemente. Los casos como los que mencionás se escribirían
usando if ... else if ... else .... No estoy en contra de agregar switch
para números, pero habría que determinar cómo.

El motivo es que el switch es el eliminador de los tipos variant, que están
definidos como una unión disjunta de varios casos. Por ejemplo, los colores
en Gobstones ya vienen predefinidos, pero internamente están definidos así:

type Color is variant { case Azul {} case Negro {} case Rojo {} case Verde
{}}

*Nota:* al menos en la filosofía de este intérprete los tipos record
también son casos particulares de tipos variant, que tienen un único caso,
es decir type A is record {...} no es otra cosa que syntax sugar para type
A is variant { case A { ... } }.

Los números en Gobstones no son tipos variant: hay al menos dos formas de
pensarlos como tipos variant, y ninguna termina de cerrar.

Una manera es pensar que están construidos recursivamente, por ejemplo
usando Cero y Sucesor. Un problema de esto es que en Gobstones no queremos
trabajar con tipos de datos recursivos (mismo motivo por el cual no se
permite hacer pattern matching sobre listas). Otro problema es que en
Gobstones también hay números negativos, que tradicionalmente se construyen
en dos capas, empezando primero por los números los naturales (de manera
que un esquema simple como el de Cero y Sucesor no alcanza para Gobstones).
Otro problema es que al hacer switch (a) to { 2 -> ... }, el patrón para el
número 2 sería conceptualmente un patrón "anidado" (tipo Suc(Suc(Cero))),
cosa que no estamos permitiendo.

La otra manera es pensar que los números son un tipo variant construido con
un número infinito de constructores (0, 1, -1, 2, -2, ...). Esto se lleva
bastante bien con el resto del lenguaje, salvo por el hecho de que los
números necesariamente tienen que estar predefinidos. Creo que estoy a
favor de agregar switch sobre números con esta interpretación. En ese caso
también estoy a favor de agregar switch sobre strings, con la misma
filosofía.

**Comment by foones** [comment]
OK con ese cambio.

Algo que olvidé mencionar es que se espera que el switch sea exhaustivo (en tiempo de ejecución). Es decir que si el switch no entra por ninguna de las ramas, da BOOM.

Esto sí recuerdo que lo hablamos, pero aprovecho para confirmar que sea el comportamiento esperado.

**Comment by fidel-ml** [comment]
Si me das el pattern _, que dé BOOM feliz.
FF

2017-12-20 11:58 GMT-03:00 foones <notifications@github.com>:

> OK con ese cambio.
>
> Algo que olvidé mencionar es que se espera que el switch sea exhaustivo
> (en tiempo de ejecución). Es decir que si el switch no entra por ninguna de
> las ramas, da BOOM.
>
> Esto sí recuerdo que lo hablamos, pero aprovecho para confirmar que sea el
> comportamiento esperado.
>
>
