### ISSUE TITLE
Interfaz de entrada: varios archivos vs un solo string

### ISSUE THREAD

**Issue by faloi** [gobstones/gobstones-interpreter#2]
> @foones dice:

Una pregunta sobre un posible cambio en la interfaz: habíamos quedado en que el parser recibe un string en el que los archivos están separados por un pragma, digamos algo como:

```js
/*@FILE foo.gbs*/
<código de foo>
/*@FILE bar.gbs*/
<código de bar>
```

Estuve pensando y me parece que esta alternativa es medio propensa a errores. ¿Estarían de acuerdo con que el parser reciba un diccionario?

Algo del estilo:

```js
{
    'foo.gbs': <código de foo>,
    'bar.gbs': <código de bar>,
}
```

Me parece que es más prolijo y trae menos problemas.

**Comment by faloi** [comment]
@rodri042, no tengo claro cómo es esto ahora, pero sí me gustaría que la interfaz del CLI no cambie en nada (ver README de https://github.com/gobstones/gs-weblang-cli).

**Comment by rodri042** [comment]
Por el runner de mumuki, claro.
Hmm, entonces
- o el nuevo intérprete da el mismo output que el anterior
- o el cli lo convierte al formato legacy

En ambos casos va a haber que hacer el mismo laburo de adaptarlo, el tema
es dónde. Yo me inclino un poco más por la segunda pero no lo tengo bien
decidido aún.

**Comment by rodri042** [comment]
Ok comenté la respuesta de @faloi sin haber leído el ontopic...

Me parece mejor la idea del diccionario, sí. Pero eso inevitablemente va a hacer que o el cli cambie su interfaz de entrada o que mumuki tenga que adaptarse a la nueva interfaz

**Comment by faloi** [comment]
Podemos hacer cambios, pero la salida del CLI me parece que está buena y no quiero cambiarla sin tener una razón fuerte.

Sí hay que discutir qué hacemos con la entrada. Si la Biblioteca es un concepto semánticamente fuerte para nosotros, debería reflejarse en el input. Si solo es una cuestión de visualización, entonces hagamos un append de contenidos y ya. 

A priori yo veo una ventaja con distinguir código de Biblioteca: nos permite calcular de forma correcta la línea en la que ocurren los errores, e incluso decidir si queremos informar de manera distinta los errores de la Biblioteca.
