### ISSUE TITLE
El procedimiento para Poner debería ser `Drop` y para Sacar debería ser `Grab`

### ISSUE THREAD

**Issue by aguspina** [gobstones/gobstones-interpreter#35]
https://github.com/gobstones/gobstones-interpreter/blob/84fe759212dfd07120901d479601db341ad6f02b/src/i18n/en.js#L22

**Comment by fidel-ml** [comment]
Pablo, ¿Podés hacerlo pronto?
En inglés los comandos Poner y Sacar son Drop y Grab.
FF
