### ISSUE TITLE
Las variables no definidas como ramas dentro de un interactive program, no producen error

### ISSUE THREAD

**Issue by rodri042** [gobstones/gobstones-interpreter#37]
```
interactive program {
    asfsafsafsa -> {
        Poner(Rojo)
    }
}
```

**Comment by foones** [comment]
Las ramas del interactive program tienen la misma forma que las ramas de un case.

Cada rama de un case tiene un patrón. El patrón puede ser meramente una variable, que funciona como caso default que le da nombre a la expresión en cuestión. (En este caso `asfsafsafsa` es el nombre de la variable).

El caso default con nombre puede servir para hacer algo así:

```
case direccionProhibida() {
    Norte -> { }
    otra -> { Mover(otra) }
}
```

Pero probablemente esto no debería estar permitido en las ramas de un `interactive program`.

**Comment by fidel-ml** [comment]
No es exactamente lo mismo que una variable no definida, porque de hecho un pattern es un punto de definición de un nombre... El tema es que las teclas NO son valores en Gobstones, y entonces no tiene sentido que un patrón de tecla sea un nombre. Por eso el único default en un interactive debería ser _.

De paso, ¿cuando decís "case", querés decir "switch", no Pablo? :D

**Comment by foones** [comment]
Fue corregido en #39 .
